package xyz.cofe.xsd.om;

public sealed interface Xsd permits XsdAll,
                                    XsdAnnotation,
                                    XsdAny,
                                    XsdAnyAttribute,
                                    XsdAppinfo,
                                    XsdAttribute,
                                    XsdAttributeGroup,
                                    XsdChoice,
                                    XsdComplexContent,
                                    XsdComplexType,
                                    XsdDocumentation,
                                    XsdElement,
                                    XsdExtension,
                                    XsdField,
                                    XsdGroup,
                                    XsdImport,
                                    XsdInclude,
                                    XsdKey,
                                    XsdKeyref,
                                    XsdList,
                                    XsdNotation,
                                    XsdRedefine,
                                    XsdRestriction,
                                    XsdSchema,
                                    XsdSelector,
                                    XsdSequence,
                                    XsdSimpleContent,
                                    XsdSimpleType,
                                    XsdUnion,
                                    XsdUnique {
}
